"""Figure & plot artifacts (Milestone 67).

A ``FIGURE-*`` is a provenance-tracked plot: its generating script, the hash of
its input data, a seed, and a caption, plus the backend/image that produced it.
Figures run inside the chosen execution environment (Phase 18/21) so they are
reproducible, and they are linked in the artifact graph to the experiment they
were generated by and/or the claim they illustrate.

Captions state what is shown and the rigor level (evidence vs. verified), never
an unbacked conclusion.
"""

from __future__ import annotations

import hashlib
from datetime import UTC, datetime
from pathlib import Path

from pydantic import BaseModel, Field

from opentorus.errors import OpenTorusError
from opentorus.jsonl import append_jsonl, next_sequential_id, read_jsonl

_IMAGE_SUFFIXES = (".svg", ".png", ".pdf", ".jpg", ".jpeg")


def _utcnow() -> datetime:
    return datetime.now(UTC)


class Figure(BaseModel):
    id: str
    title: str
    caption: str = ""
    script_path: str
    image_path: str | None = None
    data_hash: str = ""
    output_hash: str | None = None
    seed: int = 0
    experiment_id: str | None = None
    claim_id: str | None = None
    backend: str | None = None
    image_ref: str | None = None
    exit_code: int = 0
    created_at: datetime = Field(default_factory=_utcnow)


def figures_dir(ot_dir: Path) -> Path:
    return ot_dir / "figures"


def _index_path(ot_dir: Path) -> Path:
    return figures_dir(ot_dir) / "index.jsonl"


def list_figures(ot_dir: Path) -> list[Figure]:
    return read_jsonl(_index_path(ot_dir), Figure)


def get_figure(ot_dir: Path, figure_id: str) -> Figure | None:
    for figure in list_figures(ot_dir):
        if figure.id == figure_id:
            return figure
    return None


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _find_image(fig_dir: Path) -> Path | None:
    candidates = [
        p for p in sorted(fig_dir.iterdir()) if p.is_file() and p.suffix.lower() in _IMAGE_SUFFIXES
    ]
    return candidates[0] if candidates else None


def stdlib_svg_script(values: list[float], *, title: str = "figure") -> str:
    """A deterministic, dependency-free plot script (writes ``figure.svg``).

    Useful for tests and for users without matplotlib; real plots typically use
    matplotlib with a headless (``Agg``) backend inside the chosen environment.
    """
    return (
        "import json\n"
        f"VALUES = {list(values)!r}\n"
        f"TITLE = {title!r}\n"
        "SEED = 0\n"
        "\n"
        "def main() -> None:\n"
        "    width, height = 320, 200\n"
        "    n = len(VALUES) or 1\n"
        "    top = max(VALUES + [1.0])\n"
        "    bars = []\n"
        "    for i, v in enumerate(VALUES):\n"
        "        bw = width / n\n"
        "        bh = (v / top) * (height - 20)\n"
        "        x = i * bw\n"
        "        y = height - bh\n"
        "        bars.append(\n"
        '            f\'<rect x="{x:.2f}" y="{y:.2f}" width="{bw - 2:.2f}" \'\n'
        '            f\'height="{bh:.2f}" fill="#3b6ea5" />\'\n'
        "        )\n"
        "    svg = (\n"
        '        f\'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" \'\n'
        "        f'height=\"{height}\"><title>{TITLE}</title>' + ''.join(bars) + '</svg>'\n"
        "    )\n"
        "    with open('figure.svg', 'w', encoding='utf-8') as fh:\n"
        "        fh.write(svg)\n"
        "    print(json.dumps({'seed': SEED, 'kind': 'figure', 'bars': len(VALUES)}))\n"
        "\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )


def _run_plot(ot_dir, config, fig_dir: Path, environment: str | None, timeout: int):
    from opentorus.execution import ExecutionRequest, RunLimits, select_backend

    image: str | None = None
    command = "python plot.py"
    if environment is not None:
        from opentorus.execution.environments import resolve_environment

        env = resolve_environment(ot_dir, environment)
        image = env.image
        command = env.default_command.replace("run.py", "plot.py").replace("run.jl", "plot.jl")

    backend = select_backend(config, needs_image=image is not None)
    if image is not None and not getattr(backend, "requires_image", False):
        from opentorus.tools.shell import ShellResult

        return (
            ShellResult(
                command=command,
                stdout="",
                stderr=(
                    f"Environment '{environment}' needs a container runtime, but none "
                    "is available; figure not generated."
                ),
                exit_code=127,
            ),
            backend,
            image,
        )

    request = ExecutionRequest(
        command=command,
        workdir=fig_dir,
        image=image,
        network=False,
        limits=RunLimits(timeout=timeout),
    )
    return backend.run(request), backend, image


def new_figure(
    ot_dir: Path,
    title: str,
    *,
    plot_script: str,
    caption: str,
    experiment_id: str | None = None,
    claim_id: str | None = None,
    data: bytes | str = b"",
    seed: int = 0,
    environment: str | None = None,
    timeout: int = 60,
) -> Figure:
    """Generate a reproducible, captioned, graph-linked figure artifact."""
    base = figures_dir(ot_dir)
    base.mkdir(parents=True, exist_ok=True)
    figure_id = next_sequential_id("FIGURE", len(list_figures(ot_dir)))
    fig_dir = base / figure_id
    fig_dir.mkdir(parents=True, exist_ok=True)

    (fig_dir / "plot.py").write_text(plot_script, encoding="utf-8")
    data_bytes = data.encode("utf-8") if isinstance(data, str) else data
    if data_bytes:
        (fig_dir / "data.bin").write_bytes(data_bytes)

    config = _load_config(ot_dir)
    result, backend, image = _run_plot(ot_dir, config, fig_dir, environment, timeout)

    image_path: str | None = None
    output_hash: str | None = None
    produced = _find_image(fig_dir)
    if produced is not None:
        image_path = f"figures/{figure_id}/{produced.name}"
        output_hash = _sha256(produced.read_bytes())

    figure = Figure(
        id=figure_id,
        title=title,
        caption=caption,
        script_path=f"figures/{figure_id}/plot.py",
        image_path=image_path,
        data_hash=_sha256(data_bytes),
        output_hash=output_hash,
        seed=seed,
        experiment_id=experiment_id,
        claim_id=claim_id,
        backend=backend.name,
        image_ref=image if getattr(backend, "requires_image", False) else None,
        exit_code=result.exit_code,
    )
    append_jsonl(_index_path(ot_dir), figure)

    from opentorus.research.graph import add_edge

    if experiment_id:
        add_edge(
            ot_dir,
            figure_id,
            experiment_id,
            "generated_by",
            rationale="Figure from experiment.",
        )
    if claim_id:
        add_edge(
            ot_dir,
            figure_id,
            claim_id,
            "explains",
            rationale="Figure illustrates the claim.",
        )

    return figure


def regenerate_figure(
    ot_dir: Path, figure_id: str, *, timeout: int = 60
) -> tuple[bool, str | None]:
    """Re-run a figure's script and report whether the output hash is unchanged.

    Returns ``(deterministic, new_output_hash)``. The recorded figure metadata is
    not mutated; this is a reproducibility check, not an overwrite of provenance.
    """
    figure = get_figure(ot_dir, figure_id)
    if figure is None:
        raise OpenTorusError(f"No figure with id '{figure_id}'.")
    fig_dir = figures_dir(ot_dir) / figure_id
    config = _load_config(ot_dir)
    _run_plot(ot_dir, config, fig_dir, _environment_of(figure), timeout)
    produced = _find_image(fig_dir)
    if produced is None:
        return False, None
    new_hash = _sha256(produced.read_bytes())
    return new_hash == figure.output_hash, new_hash


def _environment_of(figure: Figure) -> str | None:
    # Figures do not persist the environment name (only the resolved image ref);
    # regeneration uses the workspace default backend, which is sufficient for the
    # local/headless case and honest about container needs otherwise.
    return None


def _load_config(ot_dir: Path):
    from opentorus.research.experiments import _load_config as _load

    return _load(ot_dir)
